# Generated by Django 3.2 on 2024-04-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroCreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MicroCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('rejected_at', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('delay_days', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('penalities_rate', models.FloatField(blank=True, null=True)),
                ('paid_capital', models.FloatField(default=0.0)),
                ('paid_interests', models.FloatField(default=0.0)),
                ('remaining_capital', models.FloatField(default=0.0)),
                ('remaining_interests', models.FloatField(default=0.0)),
                ('penalities_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('remaining_amount', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_microcredit', to='authentication.user')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_microcredit', to='authentication.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_microcredit', to='authentication.user')),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.microcredittype')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.period')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_microcredit', to='authentication.user')),
            ],
        ),
    ]
