# Generated by Django 3.2 on 2024-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20240417_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcredit',
            name='status',
            field=models.CharField(
                choices=[('INITIAL', 'Initial'),
                         ('PENDING', 'Pending'),
                         ('PAID', 'Paid'),
                         ('CANCELLED', 'Cancelled'),
                         ('REJECTED', 'Rejected')],
                default='INITIAL',
                max_length=50),
        ),
    ]
