# Generated by Django 3.2 on 2024-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_microcredit_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microcredit',
            old_name='penalities_amount',
            new_name='interest_amount',
        ),
        migrations.RenameField(
            model_name='microcredit',
            old_name='penalities_rate',
            new_name='penalties_rate',
        ),
        migrations.AddField(
            model_name='microcredit',
            name='penalties_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
