# Generated by Django 3.2 on 2024-04-17 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0004_auto_20240417_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcredit',
            name='created_by',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_microcredit',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
