# Generated by Django 3.2 on 2024-04-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20240417_1318'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
