# Generated by Django 3.2 on 2024-04-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20240417_1318'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
